### ISSUE TITLE
It's normalize or it's reset?

### ISSUE THREAD

**Issue by Grawl** [Andy-set-studio/modern-css-reset#11]
Hello! It's perfect idea to store so much good practices in a single CSS file available from NPM.

But some styles can cause a problems.

## 1. I do not want to use all images as `block`. Sometimes I want to inline an image, and browser default is `inline`.

```css
/* Make images easier to work with */
img {
  max-width: 100%;
  display: block;
}
```

I suggest to remove `display: block` from here.

## 2. I do not always want to get some margins somewhere in `article`.

I can use this tag for very custom design, and top margin on each child is not what I want. If I want vertical margins between elements, I use `<h1>` and `<p>`.

```css
/* Natural flow and rhythm in articles by default */
article > * + * {
  margin-top: 1em;
}
```

I suggest to remove this part.

---

All other code is amazing, I want to use it on every website I make.
