### ISSUE TITLE
Proposal: changes to lists 

### ISSUE THREAD

**Issue by Andy-set-studio** [Andy-set-studio/modern-css-reset#30]
Right now, the reset removes all padding, margin and list styles from lists that have a class attribute. This is causing problems in the community and it's something I'd like to remedy.

## Proposed change

I propose that margin and padding are left as they are. They can be removed on a per-context basis, as required. The immediate removal is **my preference** and as this thing has _exploded_ in popularity, that really doesn't hold water anymore.

With those removed, I also propose that list styles are only removed when the list has a `role` of `list` on it, like so:

```html
<ul role="list"></ul>
``` 

This is because, frustratingly, the [`list-style: none` rule can cause problems for assistive technology](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html).

## Old CSS

```css

/* Remove default padding */
ul[class],
ol[class] {
  padding: 0;
}

/* Remove default margin */
body,
h1,
h2,
h3,
h4,
p,
ul[class],
ol[class],
figure,
blockquote,
dl,
dd {
  margin: 0;
}

/* Remove list styles on ul, ol elements with a class attribute */
ul[class],
ol[class] {
  list-style: none;
}
```

## New, proposed CSS

```css
/* Remove default margin */
body,
h1,
h2,
h3,
h4,
p,
figure,
blockquote,
dl,
dd {
  margin: 0;
}

/* Remove list styles on ul, ol elements with a list role, which suggests default styling will be removed */
ul[role="list"],
ol[role="list"] {
  list-style: none;
}
```

Comments welcome.
