### ISSUE TITLE
Add default scroll-margin-top value

### ISSUE THREAD

**Issue by jdbann** [Andy-set-studio/modern-css-reset#38]
I saw @hankchizljaw's [tweet](https://twitter.com/piccalilli_/status/1352270504577675265) and thought this might be a very sensible thing to include...

Include a default `scroll-margin-top` value for any element with an `id` attribute.

```css
[id] {
  scroll-margin-top: 2ex;
}
```
