### ISSUE TITLE
Resetting <address>

### ISSUE THREAD

**Issue by renestalder** [Andy-set-studio/modern-css-reset#40]
In your reset, I made a slight addition by adding the `address` selector to the resets that is used for the inputs and buttons. The address element, by default, is rendered italic.

e.g.

```css
/* Inherit fonts for inputs and buttons */
input,
button,
textarea,
select,
address {
  font: inherit;
}
```

You open for a PR of this or does it have any negative effects?
