### ISSUE TITLE
Undo button styles for buttons with a class attribute

### ISSUE THREAD

**Issue by FrDH** [Andy-set-studio/modern-css-reset#9]
Really nice usage of the `[class]` attribute :)
In my project, I added one for removing button styles from buttons with a class attribute.

````css
button[class] {
    padding: 0;
    margin: 0;
    border: none;
    line-height: inherit;
    color: inherit;
    background: none;
}
````
